language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  api_key:
    secure:
      put: ocSEip8yAT8LjJ7rI2KSmU6EF141rm3giLIJp1sNbrZ4ewx2Tjnkq/e5VmbWN/kdd9EvSRCMngZXVfdGpLadUp8JLoR7JI4C9AjGmq5bIa7sB+dsUzh3NAlw50kqfMGhJPAGkuvjs1g0thyp/2VO9sCYZJUg7Ysfk1w01LFxCh3XS772XTH3ZmIfwt+TUMLn4D17465U0aZwibX6TQTlSyAcFlxGlavTJMuJ71SMrnpU2mpZgPh1vm9tiu8mYazg8ZSz7hxp5K5AKV+NQw1KdqarDqmMgGPO5AQGKsrhtDu281F9TyGT7YMTMpaONAqJmfvwQ227s13cK5XyyTaJHuk+CGAej39qxpunQmCCPBu5UtZnVprz2LwAEfSn7BmTy2RO/XpXFZg/hI8WXE3K4ZWl2vgqIk3dnGrBS4csuWy6nAbwkvhxmgGXHq87DC2xT1hwjzqV8+8AV2DW4Y4ijwIZj8IEhxghXuch2fx50cpan/G4AVreMCe7LINL3zl6NEZp7x+fz5vAAhdHwiH59Ix2AXHhfrQm1c378oDFng3No91ZRKj45u51xmQKJmqK/XtXQOCdrQXabEyZw8M4Ay6U7qWiqWXWbASOo1/JcHQLAZPapysSGTDNFuHBS6eZI95DGp6v0TpbBTto+ozAch6YNm7+/JZSu7o+WfKGBbM=
  app: 
    name: quiz-journey
  on:
    repo: Winyumi/quiz-journey
